/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se;

import java.util.Random;
import java.util.Scanner;

public class AppCLI  {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("Welcome to Green Travel Tracker!");
        System.out.println("Press 1 for Carbon Emission Calculator");
        System.out.println("Press 2 for Transport Route Finder ");
        System.out.print("Enter your choice: ");
        
        int choice = scanner.nextInt();
        
        switch(choice) {
            case 1:
            	 CarbonFootPrintCalculator.run();
                break;
            case 2:
                TransportRouteFinder.run();
                break;
            default:
                System.out.println("Invalid choice!");
        }
        String[] sentences = {
            "Plan your route: Before you embark on your journey, plan your route thoroughly. Familiarize yourself with the roads, potential stops, and alternative routes in case of unexpected situations.",
            "Check your vehicle: Ensure your vehicle is in good condition before hitting the road. Check the tires, brakes, lights, and fluid levels. Regular maintenance can prevent breakdowns during your journey.",
            "Wear protective gear: Whether you're riding a motorcycle or driving a car, always wear appropriate protective gear. This includes helmets, gloves, jackets, and sturdy footwear. Safety gear can significantly reduce the risk of injury in case of accidents.",
            "Stay alert: Pay attention to your surroundings while traveling. Avoid distractions such as texting or using your phone while driving. Stay vigilant for road hazards, changing weather conditions, and other vehicles.",
            "Take regular breaks: Long journeys can be exhausting, both physically and mentally. Take regular breaks to rest, stretch your legs, and hydrate. Fatigue can impair your reaction time and decision-making abilities, so it's essential to stay fresh and alert.",
            "Obey traffic laws: Follow traffic rules and regulations at all times. Respect speed limits, yield signs, and traffic signals. Reckless driving not only endangers yourself but also others on the road.",
            "Stay hydrated and nourished: Maintain proper hydration and nutrition throughout your journey. Pack enough water and healthy snacks to keep your energy levels up. Avoid excessive caffeine or sugary drinks, as they can lead to dehydration and fatigue..",
            "Keep emergency supplies: Prepare an emergency kit with essentials such as a first-aid kit, flashlight, batteries, blankets, and tools for minor repairs. Having these supplies on hand can help you handle unexpected situations more effectively.",
            "Stay updated on weather conditions: Check the weather forecast before you travel, especially if you're embarking on a long journey. Be prepared for changing weather conditions and adjust your plans accordingly. Avoid traveling in severe weather if possible.",
            "Inform someone of your itinerary: Let a trusted friend or family member know about your travel plans, including your route, expected arrival time, and contact information. In case of emergencies, they can provide assistance or alert authorities if needed."
        };

        // Create a Random object to print tips
        Random random = new Random();
        System.out.println("*****************TIPS WHILE TRAVELLING****************************");
        // Print 3 random Tips
        for (int i = 0; i < 3; i++) {
            // Generate a random index within the range of the array length
            int index = random.nextInt(sentences.length);
            System.out.println("********************************************");
            // Print the Tips at the randomly generated index
        
            System.out.println(sentences[index]);
        }
        scanner.close();
        
   }
}
        